/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasrezky;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class menuadm extends javax.swing.JFrame {

    private void kosong_kolom(){
        txtidbuku.setText(null);
        txtjudul.setText(null);
        txtpenerbit.setText(null);
        txtjumlah.setText(null);
    }
    private void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Buku");
        model.addColumn("Judul");
        model.addColumn("Penerbit");
        model.addColumn("Jumlah Halaman");
    
    try{
        String sql = "SELECT * FROM buku";
        java.sql.Connection conn = (Connection)Connect.getKoneksi();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
    
        while (res.next()){
            model.addRow(new Object[]{res.getString(1),
                                      res.getString(2),
                                      res.getString(3),
                                      res.getString(4)});
        }
        tabelData1.setModel(model);
    } catch (SQLException e){
        System.out.println("Error : " + e.getMessage());
    }
    }
    public menuadm() {
        initComponents();
        tampil_data();
        kosong_kolom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidbuku = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidbuku.setBorder(null);
        txtidbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidbukuActionPerformed(evt);
            }
        });
        getContentPane().add(txtidbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, 40));
        txtidbuku.setOpaque(false);
        txtidbuku.setBackground(new java.awt.Color(0,0,0,1));

        txtjudul.setBorder(null);
        getContentPane().add(txtjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, 40));
        txtjudul.setBackground(new java.awt.Color(0,0,0,1));

        txtpenerbit.setBorder(null);
        txtpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenerbitActionPerformed(evt);
            }
        });
        getContentPane().add(txtpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, 40));
        txtpenerbit.setBackground(new java.awt.Color(0,0,0,1));

        txtjumlah.setBorder(null);
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 200, 40));
        txtjumlah.setBackground(new java.awt.Color(0,0,0,1));

        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 540, 90, 80));
        update.setOpaque(false);
        update.setContentAreaFilled(false);
        update.setBorderPainted(false);

        tambah.setBorder(null);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 80, 80));
        tambah.setOpaque(false);
        tambah.setContentAreaFilled(false);
        tambah.setBorderPainted(false);

        hapus.setBorder(null);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 80, 80));
        hapus.setOpaque(false);
        hapus.setContentAreaFilled(false);
        hapus.setBorderPainted(false);

        tabelData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelData1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 530, 330));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MENU ADMIN.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(864, 634));
        jLabel2.setMinimumSize(new java.awt.Dimension(864, 634));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 864, 634));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidbukuActionPerformed

    private void txtpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenerbitActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       try{
   
                String sql = "UPDATE buku SET id_buku='"+txtidbuku.getText()+"',judul='"
                                                         +txtjudul.getText()+"',penerbit='"
                                                         +txtpenerbit.getText()+"',jumlah_halaman='"
                                                         +txtjumlah.getText()+"' WHERE id_buku='"+txtidbuku.getText()+"'";
                java.sql.Connection conn = (Connection)Connect.getKoneksi();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
    //            sql = String.format(sql, no, nama, partai, kabinet, periode);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
                kosong_kolom();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
    }//GEN-LAST:event_updateActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        try{
            if (txtidbuku.getText().equals("") ||txtjudul.getText().equals("")|| txtpenerbit.getText().equals("")|| txtjumlah.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Harap Isi Semua Data!");
            }else{
                if (txtjumlah.getText().contains("") || txtjumlah.getText().contains("")){
                    String sql = "INSERT INTO buku VALUES ('"+txtidbuku.getText()+"','"
                                                               +txtjudul.getText()+"','"
                                                               +txtpenerbit.getText()+"','"
                                                               +txtjumlah.getText()+"')";
                    java.sql.Connection conn = (Connection)Connect.getKoneksi();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                } else {
                    JOptionPane.showMessageDialog(null, "Format Jumlah halaman harus berupa angka");
                }
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_kolom();
    }//GEN-LAST:event_tambahActionPerformed

    private void tabelData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelData1MouseClicked
       int baris = tabelData1.rowAtPoint(evt.getPoint());
       
        String id = tabelData1.getValueAt(baris, 0).toString();
        txtidbuku.setText(id);

        String Judul = tabelData1.getValueAt(baris, 1).toString();
        txtjudul.setText(Judul);

        String Penerbit = tabelData1.getValueAt(baris, 2).toString();
        txtpenerbit.setText(Penerbit);

        String Jumlah = tabelData1.getValueAt(baris, 3).toString();
        txtjumlah.setText(Jumlah);
    }//GEN-LAST:event_tabelData1MouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try{
            String sql = "DELETE FROM buku WHERE id_buku='"+txtidbuku.getText()+"'";
            java.sql.Connection conn = (Connection)Connect.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
            kosong_kolom();
            tampil_data();
    }//GEN-LAST:event_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new loginadmin().show();
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuadm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelData1;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtidbuku;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
